language: cpp

matrix:
  include:
    - os: linux
      env: PROJECT="Osi --no-prompt" FETCH=true
    - os: linux
      env: PROJECT="Osi@master" FETCH=true
    - os: linux
      env: PROJECT="https://github.com/tkralphs/Osi@stable/0.108" FETCH=true
    - os: linux
      env: PROJECT="https://github.com/tkralphs/Osi@master" FETCH=false
    - os: linux
      env: PROJECT="Osi --no-prompt" FETCH=false
    - os: linux
      addons:
        apt:
          packages:
          - gfortran
      env: PROJECT="SYMPHONY@WS" FETCH=false
    - os: osx
      env: PROJECT="Osi --no-prompt" FETCH=false

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ x`brew list | fgrep bash` != x'bash' ]; then brew install bash; fi; brew update; fi

script:
  - if [ $FETCH = true ]; then bash ./coinbrew fetch $PROJECT; fi
  - bash ./coinbrew build $PROJECT
